/**
 * TaskRouterEventTypes represents all possible values from event type of
 * all events generated by TaskRouter.
 */
export enum TaskRouterEventTypes {
  /* Task Events */
  taskCreated = 'task.created',
  taskUpdated = 'task.updated',
  taskCanceled = 'task.canceled',
  taskWrapup = 'task.wrapup',
  taskCompleted = 'task.completed',
  taskDeleted = 'task.deleted',
  taskSystemDeleted = 'task.system-deleted',
  /* Reservation Events */
  reservationCreated = 'reservation.created',
  reservationAccepted = 'reservation.accepted',
  reservationRejected = 'reservation.rejected',
  reservationTimeout = 'reservation.timeout',
  reservationCanceled = 'reservation.canceled',
  reservationRescinded = 'reservation.rescinded',
  reservationCompleted = 'reservation.completed',
  /* Task Queue Events */
  taskQueueCreated = 'task-queue.created',
  taskQueueDeleted = 'task-queue.deleted',
  taskQueueEntered = 'task-queue.entered',
  taskQueueTimeout = 'task-queue.timeout',
  taskQueueMoved = 'task-queue.moved',
  /* Workflow Events */
  workflowTargetMatched = 'workflow.target-matched',
  workflowEntered = 'workflow.entered',
  workflowTimeout = 'workflow.timeout',
  workflowSkipped = 'workflow.skipped',
  /* Worker Events */
  workerCreated = 'worker.created',
  workerActivityUpdate = 'worker.activity.update',
  workerAttributesUpdate = 'worker.attributes.update',
  workerCapacityUpdate = 'worker.capacity.update',
  workerChannelAvailabilityUpdate = 'worker.channel.availability.update',
  workerDeleted = 'worker.deleted'
}
